load 'db/seeds/admin_user_seeds.rb'
load 'db/seeds/user_seeds.rb'
load 'db/seeds/ingredient_seeds.rb'
load 'db/seeds/recipe_seeds.rb'
load 'db/seeds/event_type_seeds.rb'
load 'db/seeds/date_frequency_seeds.rb'